"""
predict.py

Purpose:
--------
Handles inference logic for the AI Comment Analytics & Moderation System.
This module:
- Loads trained ML artifacts
- Applies preprocessing
- Performs multi-label prediction
- Uses a hybrid approach (ML + rule-based overrides)
"""

import joblib
from preprocess import clean_text

# --------------------------------------------------
# CONFIGURATION
# --------------------------------------------------

LABEL_COLUMNS = [
    "insult",
    "threat",
    "hate",
    "harassment",
    "love",
    "support"
]

THRESHOLD = 0.5

# Clearly positive phrases to reduce false positives
POSITIVE_PHRASES = [
    "too good",
    "very good",
    "excellent",
    "awesome",
    "great job",
    "well done",
    "nice work",
    "love this",
    "amazing",
    "super",
    "fantastic"
]

# --------------------------------------------------
# LOAD TRAINED ARTIFACTS
# --------------------------------------------------

# These files are generated by train.py
model = joblib.load("model/toxic_model.pkl")
vectorizer = joblib.load("model/vectorizer.pkl")

# --------------------------------------------------
# PREDICTION FUNCTION
# --------------------------------------------------

def predict_labels(comment: str) -> dict:
    """
    Predicts toxic and positive labels for a given comment.

    Parameters:
    -----------
    comment : str
        The input comment text.

    Returns:
    --------
    dict
        Dictionary of detected labels with confidence scores.
        Example:
        {
            "insult": 0.82,
            "hate": 0.67
        }
    """

    # Normalize and clean text
    cleaned_comment = clean_text(comment.lower())

    # --------------------------------------------------
    # RULE-BASED POSITIVE OVERRIDE (INDUSTRY PRACTICE)
    # --------------------------------------------------
    for phrase in POSITIVE_PHRASES:
        if phrase in cleaned_comment:
            return {
                "love": 0.95,
                "support": 0.85
            }

    # --------------------------------------------------
    # ML-BASED PREDICTION
    # --------------------------------------------------
    vectorized_text = vectorizer.transform([cleaned_comment])
    probabilities = model.predict_proba(vectorized_text)[0]

    predictions = {}

    for label, probability in zip(LABEL_COLUMNS, probabilities):
        if probability >= THRESHOLD:
            predictions[label] = round(float(probability), 2)

    return predictions
